#
# ███████╗███████╗███████╗██╗  ██╗     ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗
# ██╔════╝██╔════╝██╔════╝██║  ██║    ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝
# ███████╗█████╗  ███████╗███████║    ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
# ╚════██║██╔══╝  ╚════██║██╔══██║    ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
# ███████║███████╗███████║██║  ██║    ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
# ╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝
#
# Smart session manager for the terminal
# https://github.com/joshmedeski/sesh

strict_mode = false

[default_session]
startup_command = "nvim +GoToFile"
preview_command = "eza -1 --all --git --icons --color=always {}"

[[session]]
name = " home"
path = "~"
disable_startup_command = true

[[session]]
name = " downloads"
path = "~/Downloads"
startup_command = "y"

[[session]]
name = "󰩃 frenchie_com"
path = "~/github/frenchiebulldog/frenchie"
preview_command = "bat --language=md --style=snip --color=always ~/github/frenchiebulldog/frenchie/README.md"

[[session]]
name = "󰊠 ghostty config"
path = "~/.config/ghostty/"
preview_command = "bat --language=bash --style=snip --color=always ~/.config/ghostty/config"
startup_command = "nvim config"

[[session]]
name = " zshrc config"
path = "~"
preview_command = "bat --language=bash --style=snip --color=always ~/.zshrc"
startup_command = "nvim ~/.zshrc"

[[session]]
name = " neovim config"
path = "~/.config/nvim/"
startup_command = "nvim ."

[[session]]
name = "󱐋 sesh config"
path = "~/.config/sesh/"
startup_command = "nvim sesh.toml"
preview_command = "bat --language=toml --style=snip --color=always ~/.config/sesh/sesh.toml"

[[session]]
name = " tmux config"
path = "~/.config/tmux/"
startup_command = "nvim tmux.conf"
preview_command = "bat --language=bash --style=snip --color=always ~/.config/tmux/tmux.conf"
